//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCampsite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCampsite()
        {
            this.tComment = new HashSet<tComment>();
            this.tOptionCase = new HashSet<tOptionCase>();
            this.tTent = new HashSet<tTent>();
            this.tMember1 = new HashSet<tMember>();
            this.tTag = new HashSet<tTag>();
        }
    
        public int fCampsiteID { get; set; }
        public int fMemberID { get; set; }
        public string fCampsiteName { get; set; }
        public string fCampsitePhone { get; set; }
        public string fCampsiteArea { get; set; }
        public string fCampsiteCity { get; set; }
        public string fCampsiteAddress { get; set; }
        public string fCampsiteIntroduction { get; set; }
        public string fCampsiteAltitude { get; set; }
        public string fCampsiteClosedDay { get; set; }
        public string fCampsiteCheckInTime { get; set; }
        public string fCampsiteCheckOutTime { get; set; }
    
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tComment> tComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOptionCase> tOptionCase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTent> tTent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMember> tMember1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTag> tTag { get; set; }
    }
}
