//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tComment()
        {
            this.tMember1 = new HashSet<tMember>();
        }
    
        public int fCommentID { get; set; }
        public int fMemberID { get; set; }
        public int fCampsiteID { get; set; }
        public string fComment { get; set; }
        public int fCommentScore { get; set; }
        public System.DateTime fCommentTime { get; set; }
    
        public virtual tCampsite tCampsite { get; set; }
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMember> tMember1 { get; set; }
    }
}
