//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOptionCase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOptionCase()
        {
            this.tRent = new HashSet<tRent>();
        }
    
        public int fOptionID { get; set; }
        public int fCampsiteID { get; set; }
        public string fOptionName { get; set; }
        public int fOptionPrice { get; set; }
    
        public virtual tCampsite tCampsite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRent> tRent { get; set; }
    }
}
