//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOrder()
        {
            this.tBooked = new HashSet<tBooked>();
            this.tRent = new HashSet<tRent>();
        }
    
        public int fOrderID { get; set; }
        public int fMemberID { get; set; }
        public string fClinetName { get; set; }
        public string fClinetEmail { get; set; }
        public string fClinetPhone { get; set; }
        public int fOrderPrice { get; set; }
        public string fOrderComment { get; set; }
        public bool fOrderIsPaid { get; set; }
        public System.DateTime fOrderCreatedTime { get; set; }
    
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBooked> tBooked { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRent> tRent { get; set; }
    }
}
